### ISSUE TITLE
Sidebar does not look good on small window heights

### ISSUE THREAD

**Issue by Simon-Laux** [garredow/kaiware#1]
<img width="287" alt="Screenshot 2021-12-08 at 19 34 47" src="https://user-images.githubusercontent.com/18725968/145264599-220ee5e0-77fc-4303-a5ad-249792736b75.png">

**Comment by garredow** [comment]
Fixed with https://github.com/garredow/kaiware/commit/be375a50f84597f0e5dae8d13011f30b2466cd28
