### ISSUE TITLE
Suggestion: use a primary "accent" color for buttons

### ISSUE THREAD

**Issue by Simon-Laux** [garredow/kaiware#11]
Currently the install & download buttons look like they were disabled, most notable in the darker themes:

<img width="400" alt="Screenshot 2021-12-09 at 00 20 40" src="https://user-images.githubusercontent.com/18725968/145306710-2cb45b47-34dc-4d9d-9cdd-92219b0546c7.png">

maybe something like this:
<img width="400" alt="Screenshot 2021-12-09 at 00 27 58" src="https://user-images.githubusercontent.com/18725968/145307429-e33a8c2a-e37b-4623-9ef5-58dc355b171f.png">
(maybe a more vibrant color than this?)

**Comment by garredow** [comment]
Added option for custom accent color in https://github.com/garredow/kaiware/commit/d4d4225429db8c328de4345f202e6f3c49a847f7
