### ISSUE TITLE
[Feature Proposal] Search for apps

### ISSUE THREAD

**Issue by Simon-Laux** [garredow/kaiware#2]
the search should search for apps.

If you want to make it advanced it could give all apps a score how much they match, like checking for title, tags, category, description and giving those matches a different weight so matching title is displayed higher up than only matching description.

Or just use a premade solution like https://www.npmjs.com/package/lunr

**Comment by garredow** [comment]
Added search functionality with commit https://github.com/garredow/kaiware/commit/ba57baeedfc726a37f3ba97b23f6d4a1f7a03eb4
