### ISSUE TITLE
Disable installation buttons when no device is connected

### ISSUE THREAD

**Issue by Simon-Laux** [garredow/kaiware#9]
At best with an tooltip/popover on hover that informs the user that they need to connect their device to perform the installation.

<img width="618" alt="Screenshot 2021-12-08 at 22 55 05" src="https://user-images.githubusercontent.com/18725968/145290635-6e32a01e-6c6b-427d-b289-e39f4654f153.png">

<img width="618" alt="Screenshot 2021-12-08 at 22 55 53" src="https://user-images.githubusercontent.com/18725968/145290799-1152fa0c-d021-4206-82f5-1321d61bbf21.png">

**Comment by garredow** [comment]
Fixed with https://github.com/garredow/kaiware/commit/e3b3d4f58888596fe314ec9fddadbce4bc6b25ae and https://github.com/garredow/kaiware/commit/80ca6b44bd0323dc551759f685c2ae5300dafa4b
